### ISSUE TITLE
Chaining/combining Patterns

### ISSUE THREAD

**Issue by tbsexton** [rgiordan/paragami#70]
Curious if it would be possible to enforce multiple patterns on a single parameter, or (better yet), enforce conditional patterns. 

e.g. in the case of observing random walks on a graph (say a loss is known, given some random walk observation and an adjacency matrix/etc parameter). I might be able to say the normalized graph laplacian $L_n$ is PSDMatrix pattern, but that a known modification to it gives us the row-stochastic transition matrix:

 $P = I-D^{-\frac{1}{2}}L_n D^{\frac{1}{2}}$

(where D is the diagonal degree matrix)...That would be on a simplex, given each row sums to 1. It would be useful to enforce both constraints on the same free-parameter.

**Comment by rgiordan** [comment]
So, if I understand you correctly, is the problem that there are PSD matrices $A$ such that $I-D^{-\frac{1}{2}} A D^{\frac{1}{2}}$ may not be a valid transition matrix (i.e., the rows may not sum to one), and there arrays of simplexes $B$ such that $D^{\frac{1}{2}} ( I - B ) D^{-\frac{1}{2}}$ is not positive definite? 

Off the top of my head, don't know whether this can dealt with easily, though I'm don't know much about graph theory.  Constrained parameters in ``paragami`` (as in Stan) are built with diffemorphisms between constrained mathematical objects and some Euclidian space. Not every mathematical object has such a diffeomorphism --- unit vectors are one a simple example of a parameter without a simple differentiable ``unconstraining function''.  I'm not sure whether valid graph Laplacians are diffemorphic with Euclidian space, but that's the way to think about it.

If you come up with something and want help implementing a pattern, let me know!

**Comment by tbsexton** [comment]
I'll honestly have to look into this a bit to learn more of the technical underpinnings! Certainly the most straight-forward thing I can think of is a constraint to the birkhoff polytope, which I have no idea about diffeomorphisms *but* I somehow doubt they exist/are know since estimating the space of permutation matrices (e.g. adjacency matrix) is [a big problem ](https://arxiv.org/abs/1710.09508) of late. 

However, I think my original question is more of a work-around: can one constrained parameter *depend* on another having a different constraint? For instance, I know that $P$ is on a simplex/row-stochastic, and that it depends on $L_n$ which we know is PSD. 

If each constraint can be enforced separately, then the problem could be broken up into modular sub-units.

**Comment by rgiordan** [comment]
Thanks for the question!  I'm finally replying here though we did have a brief email exchange.  I don't see an obvious way to chain constraints together in this way, though it may be for lack of trying.

A simple example to think about might be constraining a single number to be in $[a, b]$ by combining the constraints that it be in $[a, \infty)$ and $(-\infty, b]$.  I implement the $[a, b]$ constraint by a shifted logistic function, which needs to know both endpoints.  However, if you apply the $[a, \infty)$ and $(-\infty, b]$ constraints separately, you only ever know one endpoint at a time, and it's hard for me to see how you could make that work.  

There's probably a clearer way to think about this, but I'm going to close the issue for now.  Do let me know if you come up with something!
